title: One Day Workshop for High-z Cosmological Simulations
description: A workshop focusing on high-redshift cosmological simulations, hosted at the University of Tokyo.
author: Yurina Nakazato
lang: en

favicon: /assets/images/favicon.ico

plugins:
  - jekyll-sitemap
  
google_analytics: 
theme: minima

#base_url: /high-z

# Minima social links
#twitter_username: yurinanakazato
#github_username: yurinanakazato

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - frontpage.md
  

include:
#    - _pages

exclude: 
#    - .gitignore
#    - docker-compose.yml
#    - Gemfile
#    - Gemfile.lock
#    - LICENSE
#    - README.md
