# サイト設定
title: "One Day Workshop for Star Cluster Simulations"
description: "A workshop focusing on Star Cluster Simulations"
author: "Yurina Nakazato"
lang: en

# GitHub Pages用
url: "https://yurinanakazato.github.io"  # 例: https://yurinanakazato.github.io
baseurl: "/star_cluster_simulation"                       # 例: /star_cluster_simulation

# テーマ
theme: minima

# プラグイン
plugins:
  - jekyll-sitemap

# Minimaの設定例
minima:
  date_format: "%Y-%m-%d"

# ホームページに表示するページ (Minima ではなくてもOK)
# もし複数ページをナビゲーションバーに表示したいなら使う
header_pages:
  - frontpage.md

# ビルドに含めたいフォルダ (assets や css は通常自動的に含まれます)
# include:
#   - assets
#   - css

# 除外したいファイルがあれば
# exclude:
#   - README.md
